# Generated by Django 3.2.5 on 2021-08-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bookie',
            field=models.CharField(choices=[('bet365', 'bet365.png'), ('stoiximan', 'stoiximan.png'), ('opap', 'opap.png')], default='365', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='type',
            field=models.CharField(choices=[('football', (('f_r', 'Final Result'), ('g_o_u', 'Goals over/under'), ('as_ha', 'Asian Handicap'), ('t_ca', 'Total Cards'), ('to_sc', 'To Score'), ('as_g_o_u', 'Asian Goals over/under'), ('to_r_y_c', 'To Receive Yellow Card'), ('to_r_r_c', 'To Receive Red Card'), ('to_r_c', 'To Receive Card'), ('to_as_ca', 'Total Asian Cards'), ('w_h', 'Win Handicap'))), ('basketball', (('f_r', 'Final Result'), ('h_to_h_p', 'Head to Head Points'), ('pl_p', 'Player Points'), ('t_p', 'Total Points'), ('p_a', 'Player Assists'), ('t_3_m', 'Total 3pts made'), ('p_r', 'Player Rebounds'), ('p_p_r', 'Player Points/Rebounds'), ('t_s', 'Top Scorer'), ('p_r_a', 'Player Rebounds/Assists'), ('p_p_r_a', 'Player Points/Rebounds/Assists'), ('mvp', 'MVP'), ('d_d', 'Double/Double'), ('w_h', 'Win Handicap'))), ('tennis', (('f_r', 'Final Result'), ('to_se', 'Total Sets'), ('d_fa', 'Double Faults'), ('to_ac', 'Total aces'), ('pl_ac', 'Player Aces')))], max_length=100),
        ),
    ]
