# Generated by Django 3.2.5 on 2021-08-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_auto_20210811_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bookie',
            field=models.CharField(choices=[('bet365.png', 'bet365'), ('stoiximan.png', 'stoiximan'), ('opap.png', 'opap')], default='365', max_length=100, null=True),
        ),
    ]
